spring:
  datasource:
    url: jdbc:mysql://rm-m5eg6e7vjl9v152i26o.mysql.rds.aliyuncs.com:3306/paascloud_uac?serverTimezone=UTC
    username: root
    password: Ssylqwj!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
### xxl-job admin address list, such as  "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: ${spring.application.name}
      ip: ${spring.cloud.client.ip-address}
      port: 9999

    ### xxl-job, access token
    accessToken: