spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bfe8662580f52bfcbe6d
            client-secret: 1cce0033fadf002fa242a718d26012f03554b4fc

  cloud:
    gateway:
      enabled: true
      routes:
        - id: paascloud-provider-uac
          uri: lb://paascloud-provider-uac
          predicates:
            - Path=/uac/**
#          filters:
#            - StripPrefix=1
